version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    container_name: db_mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_DATABASE=db
    ports:
      - '3306:3306'
    volumes:
      - mysql_db:/var/lib/mysql
    restart: on-failure
#  postgres_db:
#    container_name: postgres_container
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      PGDATA: /data/postgres
#    volumes:
#      - postgres_db:/data/postgres
#    ports:
#      - "5432:5432"
#    restart: on-failure

  redis:
    container_name: redis_container
    hostname: redis
    image: redis:latest
    command: --port 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis:/bitnami/redis/data
    restart: on-failure

  fastapi_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_api
#    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - fastapi_api:/backend
    depends_on:
      - mysql_db
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://root:123456@mysql_db:3306/db
      - DATABASE_TEST_URL=postgresql://postgres:password@mysql_db:3306/db_test
      - ALEMBIC_DB_URL=mysql+asyncmy://root:123456@mysql_db:3306/db
      - REDIS_URL=redis://localhost:6379
    restart: always
volumes:
  mysql_db:
  redis:
  fastapi_api:
